# Generated by Django 5.2.8 on 2025-12-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_add_scorm_suspend_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivecourseprogress',
            name='slide_started_at',
            field=models.JSONField(blank=True, default=dict, help_text='ISO timestamps keyed by slide number for when user started a slide'),
        ),
        migrations.AddField(
            model_name='interactivecourseprogress',
            name='slide_completed_at',
            field=models.JSONField(blank=True, default=dict, help_text='ISO timestamps keyed by slide number for when user completed a slide'),
        ),
        migrations.AddField(
            model_name='interactivecourseprogress',
            name='skip_attempts',
            field=models.IntegerField(default=0, help_text='Count invalid slide jump attempts'),
        ),
    ]

